mv: chirp-v4
cookie_pool: []
use_cookie: 1
save_data:
  metadata: true
  lyric: true
  cover: true
  audio: true
  video: false
send_type: 'record'
await_time: 60
auto_next: false
del_file: true
proxy:
  enable: false
  host: 127.0.0.1
  port: "7890"